name: Unit Test Coverage Report

on:
    - push
    - fork
    - pull_request

jobs:
    coverage:
        runs-on: ubuntu-latest
        name: "Generate unit test coverage report for PHP ${{ matrix.php-version }}"
        strategy:
            fail-fast: false
        env:
            XDEBUG_MODE: coverage
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: xdebug
                  tools: composer:v2
            - run: composer install
              shell: bash
            - run: composer test:coverage:xml
              shell: bash
            - uses: paambaati/codeclimate-action@v3.0.0
              env:
                  CC_TEST_REPORTER_ID: 8f57a9ffb20e7dd2ec62db92c7692a0c2dfc58577f70881d6f01096825446324
              with:
                  coverageLocations: coverage.xml:clover
            - uses: actions/upload-artifact@v2
              with:
                  name: coverage.xml
                  path: coverage.xml
